[package]
name = "dominator-static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
ego-tree = "0.6.2"
pulldown-cmark = "0.9.1"
scraper = "0.12.0"
walkdir = "2.3.2"

